In [1]:
import pandas as pd

df = pd.read_csv('experiment-results/results_c1_steering.csv')
df

     Unnamed: 0  Steered Parameter Value   Fitness       Time
0             0                 0.100000  0.884115  11.374363
1             1                 0.100000  0.886719  11.641628
2             2                 0.100000  0.899740  11.225643
3             3                 0.100000  0.885417  11.166677
4             4                 0.100000  0.885417  11.100764
..          ...                      ...       ...        ...
395         395                 3.999998  0.858073  11.210442
396         396                 3.999998  0.867188  11.062351
397         397                 3.999998  0.864583  11.101513
398         398                 3.999998  0.872396  11.117158
399         399                 3.999998  0.864583  11.127410

[400 rows x 4 columns]

In [10]:
df = df.round(3)
df

     Unnamed: 0  Steered Parameter Value  Fitness    Time
0             0                      0.1    0.884  11.374
1             1                      0.1    0.887  11.642
2             2                      0.1    0.900  11.226
3             3                      0.1    0.885  11.167
4             4                      0.1    0.885  11.101
..          ...                      ...      ...     ...
395         395                      4.0    0.858  11.210
396         396                      4.0    0.867  11.062
397         397                      4.0    0.865  11.102
398         398                      4.0    0.872  11.117
399         399                      4.0    0.865  11.127

[400 rows x 4 columns]

In [13]:
df[df['Steered Parameter Value'].round(decimals=2) == 0.4]

    Unnamed: 0  Steered Parameter Value  Fitness    Time
30          30                      0.4    0.885  11.201
31          31                      0.4    0.884  11.147
32          32                      0.4    0.893  11.165
33          33                      0.4    0.882  11.201
34          34                      0.4    0.901  11.128
35          35                      0.4    0.902  11.224
36          36                      0.4    0.895  11.197
37          37                      0.4    0.898  11.177
38          38                      0.4    0.896  11.175
39          39                      0.4    0.908  11.227

In [11]:
df.groupby('Steered Parameter Value').mean()

                         Unnamed: 0  Fitness     Time
Steered Parameter Value
0.1                             4.5   0.8885  11.2760
0.2                            14.5   0.8909  11.1789
0.3                            24.5   0.8865  11.1772
0.4                            34.5   0.8944  11.1842
0.5                            44.5   0.8908  11.1918
0.6                            54.5   0.8864  11.1423
0.7                            64.5   0.8900  11.1247
0.8                            74.5   0.8850  11.1942
0.9                            84.5   0.8892  11.1803
1.0                            94.5   0.8843  11.1344
1.1                           104.5   0.8842  11.1678
1.2                           114.5   0.8854  11.1363
1.3                           124.5   0.8790  11.1243
1.4                           134.5   0.8830  11.1510
1.5                           144.5   0.8856  11.1649
1.6                           154.5   0.8763  11.1201
1.7                           164.5   0.8785  11.1338
1.8                           174.5   0.8782  11.0736
1.9                           184.5   0.8772  11.0744
2.0                           194.5   0.8772  11.1116
2.1                           204.5   0.8785  11.1146
2.2                           214.5   0.8766  11.1539
2.3                           224.5   0.8742  11.1348
2.4                           234.5   0.8781  11.1429
2.5                           244.5   0.8735  11.1343
2.6                           254.5   0.8768  11.1246
2.7                           264.5   0.8781  11.0324
2.8                           274.5   0.8731  11.1356
2.9                           284.5   0.8752  11.1227
3.0                           294.5   0.8691  11.1086
3.1                           304.5   0.8689  11.0958
3.2                           314.5   0.8733  11.1084
3.3                           324.5   0.8719  11.0956
3.4                           334.5   0.8688  11.1175
3.5                           344.5   0.8703  11.0965
3.6                           354.5   0.8700  11.1797
3.7                           364.5   0.8653  11.1215
3.8                           374.5   0.8716  11.0987
3.9                           384.5   0.8595  11.1441
4.0                           394.5   0.8633  11.1212